class MenuItem:
    def __init__(self, item):
        if(item == 'espresso'):
            self.name = 'espresso'
            self.water = 50
            self.coffee = 18
            self.cost = 1.5
        elif(item == 'latte'):
            self.name = 'latte'
            self.water = 200
            self.coffee = 24
            self.milk = 150
            self.cost = 2.5
        elif(item == 'cappuccino'):
            self.name = 'cappuccino'
            self.water = 250
            self.coffee = 18
            self.milk = 100
            self.cost = 3
